### ISSUE TITLE
Output Schema Bug in distal-whisper Model in app.py

### ISSUE THREAD

**Issue by BenLambright** [clamsproject/app-distil-whisper-wrapper#1]
### Bug Description

When the predicted text generates an output, this output doesn't have the expected `<start> sentence <end>` organization schema. Instead, you see schema like this:
```
<|0.00|><|0.00|><|0.00|> you<|2.00|><|2.00|><|2.00|> Good evening, I'm Jim Lara. On the news hour tonight, coverage of the Salt Lake<|11.24|>...
```

When annotated, you can see sentences are not always predicted between `<start>` and `<end>` tokens, as follows:
```
<|start|><|end|><|start|> you<|end|><|start|><|end|> Good evening, I'm Jim Lara. On the news hour tonight, coverage of the Salt Lake<|start|>...
```

The current logic that handles the sentence extraction from the output, `process_output_with_enclosed_timestamps(output)`, would skip over the sentence "Good evening, I'm Jim Lara. On the news hour tonight, coverage of the Salt Lake" because it doesn't take sentences between `<end>` and `<start>` token. Therefore, this correct sentence would not be in the final output. 

### Reproduction steps

1. Go to https://github.com/clamsproject/app-distil-whisper-wrapper/blob/main/app.py
2. The issue is related to `process_output_with_enclosed_timestamps(output)` (lines 23-34) and the generation and processing of the output text on lines 134-137
3. When running this natively, two errors will occur in app.py before an output is produced. First, change `"max_new_tokens": 448` to 447 on line 125 because the model can't handle 448 tokens with the current beam size. Then, to resolve the second error, change the for loop on line 27 to `for i in range(1, len(raw_segments) - 1, 2):` because a variable in the for loop takes the value `raw_segments[i + 1]`, but this index is out of bounds with the original for loop.

### Expected behavior

Ensure that it pulls the correct sentences from the output. For example, ensure that in the previous example:
```
<|0.00|><|0.00|><|0.00|> you<|2.00|><|2.00|><|2.00|> Good evening, I'm Jim Lara. On the news hour tonight, coverage of the Salt Lake<|11.24|>...
```
"Good evening, I'm Jim Lara. On the news hour tonight, coverage of the Salt Lake" is extracted, not "you." Currently, it pulls "you" and not the correct sentence.

**Comment by keighrim** [comment]
re-opening the issue after found more problems with direct model-loading implementation. See #2 for further discussion.
